# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_ann/design_ann.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann || ORIG_REF_NAME==design_ann} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_zynq_ultra_ps_e_0_0/design_ann_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_ann_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_axi_dma_0_0/design_ann_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_axi_dma_0_0 || ORIG_REF_NAME==design_ann_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_xbar_0/design_ann_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_xbar_0 || ORIG_REF_NAME==design_ann_xbar_0} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_ps8_0_axi_periph_0/design_ann_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_ann_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_rst_ps8_0_99M_0/design_ann_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_ann_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_axi_smc_0/design_ann_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_axi_smc_0 || ORIG_REF_NAME==design_ann_axi_smc_0} -quiet] -quiet

# Block Designs: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/bd_9870.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_0/bd_9870_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_1/bd_9870_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_2/bd_9870_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_3/bd_9870_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_4/bd_9870_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_5/bd_9870_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_6/bd_9870_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_7/bd_9870_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_8/bd_9870_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_9/bd_9870_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_ann/ip/design_ann_axi_smc_1_0/design_ann_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_axi_smc_1_0 || ORIG_REF_NAME==design_ann_axi_smc_1_0} -quiet] -quiet

# Block Designs: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/bd_4e4c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_0/bd_4e4c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_1/bd_4e4c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_2/bd_4e4c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_3/bd_4e4c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_4/bd_4e4c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_5/bd_4e4c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_6/bd_4e4c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_7/bd_4e4c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_8/bd_4e4c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_9/bd_4e4c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_10/bd_4e4c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_ann/ip/design_ann_auto_ds_0/design_ann_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_auto_ds_0 || ORIG_REF_NAME==design_ann_auto_ds_0} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_auto_pc_0/design_ann_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_auto_pc_0 || ORIG_REF_NAME==design_ann_auto_pc_0} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_auto_ds_1/design_ann_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_auto_ds_1 || ORIG_REF_NAME==design_ann_auto_ds_1} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_auto_pc_1/design_ann_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_auto_pc_1 || ORIG_REF_NAME==design_ann_auto_pc_1} -quiet] -quiet

# IP: bd/design_ann/ip/design_ann_axis_ann_0_0/design_ann_axis_ann_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_ann_axis_ann_0_0 || ORIG_REF_NAME==design_ann_axis_ann_0_0} -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_zynq_ultra_ps_e_0_0/design_ann_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_zynq_ultra_ps_e_0_0/design_ann_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ann_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_ann_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_dma_0_0/design_ann_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ann_axi_dma_0_0 || ORIG_REF_NAME==design_ann_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_dma_0_0/design_ann_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ann_axi_dma_0_0 || ORIG_REF_NAME==design_ann_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_rst_ps8_0_99M_0/design_ann_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ann_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_ann_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_rst_ps8_0_99M_0/design_ann_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ann_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_ann_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_1/bd_9870_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_1/bd_9870_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_5/bd_9870_s00a2s_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_6/bd_9870_sarn_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_7/bd_9870_srn_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/bd_0/ip/ip_8/bd_9870_m00s2a_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_0/ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_1/bd_4e4c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_1/bd_4e4c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_5/bd_4e4c_s00a2s_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_6/bd_4e4c_sawn_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_7/bd_4e4c_swn_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_8/bd_4e4c_sbn_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/bd_0/ip/ip_9/bd_4e4c_m00s2a_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_axi_smc_1_0/ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_auto_ds_0/design_ann_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ann_auto_ds_0 || ORIG_REF_NAME==design_ann_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_auto_ds_0/design_ann_auto_ds_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_auto_pc_0/design_ann_auto_pc_0_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_auto_ds_1/design_ann_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_ann_auto_ds_1 || ORIG_REF_NAME==design_ann_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_auto_ds_1/design_ann_auto_ds_1_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/ip/design_ann_auto_pc_1/design_ann_auto_pc_1_ooc.xdc

# XDC: d:/Repository/ann_processor/vivado/vivado.gen/sources_1/bd/design_ann/design_ann_ooc.xdc
